title: Boris Beker
#logo: 
external:
- {title: Linkedin Profile, url: "https://www.linkedin.com/in/boris-beker/"
- {title: Tableau Profile, url: "https://public.tableau.com/app/profile/boris3213/vizzes"
#show_download: ture
theme: jekyll-theme-minimal
